repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: forbid-legacy-names
        name: Forbid legacy names
        entry: bash -c 'if rg -n --glob "!docs/naming_spec.md" "(\\blon_trop_deg\\b|\\bmadhya_deg_sid\\b|\\btz_offset\\b(?!_hours))"; then echo "Legacy names found"; exit 1; fi'
        language: system
        pass_filenames: false
